CREATE DATABASE IF NOT EXISTS `habitat_nextcloud`;

CREATE USER 'nextcloud'@'%' IDENTIFIED BY PASSWORD '${NEXTCLOUD_MYSQL_PASSWORD_HASH}';
GRANT ALL PRIVILEGES ON `habitat_nextcloud`.* TO 'nextcloud'@'%';
FLUSH PRIVILEGES;