#!/bin/sh

[ -f "NEXTCLOUD_OAUTH_CLIENT_ID_FILE" ] && export NEXTCLOUD_OAUTH_CLIENT_ID="$(cat "$NEXTCLOUD_OAUTH_CLIENT_ID_FILE")"
[ -f "NEXTCLOUD_OAUTH_CLIENT_SECRET_FILE" ] && export NEXTCLOUD_OAUTH_CLIENT_SECRET="$(cat "$NEXTCLOUD_OAUTH_CLIENT_SECRET_FILE")"

exec "$@"